### ISSUE TITLE
Refactor `getPastEvents`

### ISSUE THREAD

**Issue by phahulin** [poanetwork/bridge-monitor#24]
An error
```
2019-04-29T13:45:07.944Z (+1583ms) [getShortEventStats.js] calling foreignBridge.getPastEvents('Deposit')
2019-04-29T13:45:08.255Z [getShortEventStats.js] Error: Returned error: query returned more than 1000 results
...
```
occurs when trying to fetch past events, e.g. here https://github.com/poanetwork/bridge-monitor/blob/d5027164ad64f4ec717fbc2cb6db2673deeb28fd/getShortEventStats.js#L31

This is probably a limitation of infura, but we have to work around it.

**Comment by akolotov** [comment]
This is definitely the issue related to Infura provider. 
If you call
```
curl --data '{"method":"eth_getLogs","params":[{"fromBlock":"0x62da56","toBlock":"0x74e491","address":"0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://mainnet.infura.io
```
it will return:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32005,"message":"query returned more than 1000 results"}}
```

One of possible solution is to start using BlockScout API (https://blockscout.com/poa/dai/api_docs) to get the logs (`getLogs`) as soon as https://github.com/poanetwork/blockscout/issues/1858 is addressed.

Another solution could be to use recursively the binary search algorithm to identify a block range that will not return the error returned described above. The end block (B) found in an iteration I-1 will be used as the start block (B+1) for the next iteration to recursively find new block range.

**Comment by phahulin** [comment]
I think we shouldn't go with the blockscout route; or make it optional. Otherwise applicability of bridge-monitor becomes limited.

**Comment by akolotov** [comment]
Addressed by https://github.com/poanetwork/bridge-monitor/pull/27
