### ISSUE TITLE
[BUG] Balance of a validator cannot be checked

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-monitor#4]
There are two entities in the bridge logic:
1. Bridge validators - accounts which sent their signatures to authorize deposits and withdraws.
2. Bridge operators - accounts which send transactions in home or foreign networks.
In POA Bridge implementation 'bridge operators' for foreign network match with 'bridge validators'.
At the same time it is not mandatory that 'bridge operators' for home network  match with the list of validators. 

It cause the issue with `validators.js`: it request balances on home network for 'bridge validators' although these accounts are not 'bridge operators', so their balances will be always zero and this cause alarm raising.

As a short term solution the following could be considered: configure list of accounts which balances needs to be monitored through the list in `.env` file.

**Comment by rstormsf** [comment]
i don't understand the issue

**Comment by akolotov** [comment]
as per security audit we consider to have the same account to sign transactions on both sides of the network. So, it is not the bug any more.
