### ISSUE TITLE
Add support of new contracts

### ISSUE THREAD

**Issue by akolotov** [poanetwork/bridge-monitor#7]
As part of revisiting bridge contracts and adding support of `erc20-to-erc20` bridge mode (https://github.com/poanetwork/poa-bridge-contracts/tree/refactor_v1) it is necessary to investigate what set of changes needs to done on side of `bridge-monitor` and create set of issues in GitHub to address these changes.

**Comment by patitonar** [comment]
I'm closing this issue, It was solved by #9
